name: TestDeploy
on:
  push:
    paths:
      - .github/workflows/deployTest.yml
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: Agnija-MSBootcamp
        template: ./ARM-Templates/container-webapp-template.json