name: .NET
env:
  registryName: ms887devopsreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag: ${{ github.run_number }}


on:
  push:
    branches: [ main ]
    paths:
      - Application/**
  pull_request:
    branches: [ main ]
    paths:
      - Application/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Application/src/RazorPagesTestSample
    - name: Build
      run: dotnet build --no-restore
      working-directory: Application/src/RazorPagesTestSample
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Application/tests/RazorPagesTestSample.Tests
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login $registryName -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}}
    - name: Docker build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker push
      run: docker push $registryName/$repositoryName:$tag

